### ISSUE TITLE
V10 Urgent Warning!

### ISSUE THREAD

**Issue by p3yot3** [starwels/starwels#10]
"version" : 100000,
    "protocolversion" : 70002,
    "walletversion" : 60000,
    "balance" : 0.00000000,
    "blocks" : 30552,
    "timeoffset" : -1,
    "connections" : 5,
    "proxy" : "",
    "difficulty" : 30412271.47290681,
    "testnet" : false,
    "keypoololdest" : 1497689075,
    "keypoolsize" : 101,
    "paytxfee" : 0.00000000,
    "relayfee" : 0.00001000,
    **"errors" : "URGENT: Alert key compromised, upgrade required"**

**Comment by DATSEC** [comment]
Use the version 0.14.1

**Comment by p3yot3** [comment]
I was, but the chain was stuck. I see you have now changed the releases again now though. What branch actually works?

**Comment by p3yot3** [comment]
Or....?

**Comment by DATSEC** [comment]
All branches work
